name: auto-migrate

on:
  workflow_dispatch:
    inputs:
      formula_name:
        description: 'Target Formula'
        required: true

jobs:
  auto-migrate:
    runs-on: ubuntu-24.04-arm
    container:
      image: swr.cn-north-4.myhuaweicloud.com/harmonybrew/ci-runner:latest
      volumes:
        - /opt/node24:/__e/node24:rw,rshared
    steps:
      - name: Setup Node
        run: |
          curl -L -O https://github.com/hqzing/ohos-node/releases/download/v24.2.0/node-v24.2.0-openharmony-arm64.tar.gz
          mkdir /__e/node24/bin
          tar -zxf node-v24.2.0-openharmony-arm64.tar.gz -C /opt
          ln -s /opt/node-v24.2.0-openharmony-arm64/bin/node /__e/node24/bin/node

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install requests

      - name: Auto Migrate
        env:
          GITCODE_USER: ${{ vars.GITCODE_USER }}
          GITCODE_EMAIL: ${{ vars.GITCODE_EMAIL }}
          GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN }}
        run: |
          python3 auto-migrate.py "${{ github.event.inputs.formula_name }}"
